#!/bin/sh
of30
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`
#runApplication setFields
#runApplication $application

if [ ! -d "../ra/" ]
then
    mkdir ../ra
fi

./Allclean
cp 0/T.ra 0/T.org

for i in 1 2 3 4 5 6 7 8 9 10
do
    case $i in
	2) sed -i 's/293.16/293.25/g' 0/T.org
	   ;;
	3) sed -i 's/293.25/293.65/g' 0/T.org
	   ;;
	4) sed -i 's/293.65/294.15/g' 0/T.org
	   ;;
	5) sed -i 's/294.15/295.15/g' 0/T.org
	   ;;
	6) sed -i 's/295.15/296.15/g' 0/T.org
	   ;;
	7) sed -i 's/296.15/297.15/g' 0/T.org
	   ;;
	8) sed -i 's/297.15/298.15/g' 0/T.org
	   ;;
	9) sed -i 's/298.15/303.15/g' 0/T.org
	   ;;
	10) sed -i 's/303.15/313.15/g' 0/T.org
	   ;;
    esac
    runApplication blockMesh
    runApplication mirrorMesh
    cp 0/T.org 0/T
    foamJob -wait buoyantBoussinesqPimpleFoam
    foamLog log
    probeLocations
    sample
    cp -r ../cooledOilPipe ../ra/Ra_$i
    ./Allclean
done
echo "Done"
# ----------------------------------------------------------------- end-of-file
